version: "3.8"

services:
    backend:
        build: ./backend
        ports:
            - "5001:8080"
        env_file:
            - .env
        volumes:
            - ./backend:/app
            - /app/node_modules

    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend
        volumes:
            - ./frontend:/app
            - /app/node_modules
