/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as IdeasIndexRouteImport } from './routes/ideas/index'
import { Route as IdeasNewIndexRouteImport } from './routes/ideas/new/index'
import { Route as IdeasIdeasIdIndexRouteImport } from './routes/ideas/$ideasId/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as IdeasIdeasIdEditRouteImport } from './routes/ideas/$ideasId/edit'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/ideas/',
  path: '/ideas/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasNewIndexRoute = IdeasNewIndexRouteImport.update({
  id: '/ideas/new/',
  path: '/ideas/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeasIdIndexRoute = IdeasIdeasIdIndexRouteImport.update({
  id: '/ideas/$ideasId/',
  path: '/ideas/$ideasId/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authRouteRoute,
} as any)
const IdeasIdeasIdEditRoute = IdeasIdeasIdEditRouteImport.update({
  id: '/ideas/$ideasId/edit',
  path: '/ideas/$ideasId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '/ideas': typeof IdeasIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/ideas/$ideasId/edit': typeof IdeasIdeasIdEditRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/ideas/$ideasId': typeof IdeasIdeasIdIndexRoute
  '/ideas/new': typeof IdeasNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '/ideas': typeof IdeasIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/ideas/$ideasId/edit': typeof IdeasIdeasIdEditRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/ideas/$ideasId': typeof IdeasIdeasIdIndexRoute
  '/ideas/new': typeof IdeasNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/ideas/': typeof IdeasIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/ideas/$ideasId/edit': typeof IdeasIdeasIdEditRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/ideas/$ideasId/': typeof IdeasIdeasIdIndexRoute
  '/ideas/new/': typeof IdeasNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ideas'
    | '/profile'
    | '/ideas/$ideasId/edit'
    | '/login'
    | '/register'
    | '/ideas/$ideasId'
    | '/ideas/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ideas'
    | '/profile'
    | '/ideas/$ideasId/edit'
    | '/login'
    | '/register'
    | '/ideas/$ideasId'
    | '/ideas/new'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/ideas/'
    | '/profile/'
    | '/ideas/$ideasId/edit'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/ideas/$ideasId/'
    | '/ideas/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  IdeasIndexRoute: typeof IdeasIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  IdeasIdeasIdEditRoute: typeof IdeasIdeasIdEditRoute
  IdeasIdeasIdIndexRoute: typeof IdeasIdeasIdIndexRoute
  IdeasNewIndexRoute: typeof IdeasNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/new/': {
      id: '/ideas/new/'
      path: '/ideas/new'
      fullPath: '/ideas/new'
      preLoaderRoute: typeof IdeasNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideasId/': {
      id: '/ideas/$ideasId/'
      path: '/ideas/$ideasId'
      fullPath: '/ideas/$ideasId'
      preLoaderRoute: typeof IdeasIdeasIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/ideas/$ideasId/edit': {
      id: '/ideas/$ideasId/edit'
      path: '/ideas/$ideasId/edit'
      fullPath: '/ideas/$ideasId/edit'
      preLoaderRoute: typeof IdeasIdeasIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  IdeasIndexRoute: IdeasIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  IdeasIdeasIdEditRoute: IdeasIdeasIdEditRoute,
  IdeasIdeasIdIndexRoute: IdeasIdeasIdIndexRoute,
  IdeasNewIndexRoute: IdeasNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
